import { adminApiRequest, getAdminAccessToken, getStoredAdminAuth } from "../lib/adminApi";
function normalizeMessage(m={}){return {id:m._id||m.id,from:m.from,text:m.text||"",ts:m.ts?new Date(m.ts).getTime():Date.now(),readByCustomer:m.readByCustomer===true,readByAdmin:m.readByAdmin===true};}
function normalizeThread(t={}){const messages=(t.messages||[]).map(normalizeMessage);return {id:t.threadId||t.id||t._id,threadId:t.threadId||t.id,customerName:t.customerName||"Guest",customerEmail:t.customerEmail||"",status:t.status||"open",messages,unread:messages.filter(m=>m.from==="customer"&&!m.readByAdmin).length,last:messages[messages.length-1]||null,updatedAt:t.updatedAt?new Date(t.updatedAt).getTime():0,createdAt:t.createdAt?new Date(t.createdAt).getTime():0};}
export async function getThreads({q=""}={}){const payload=await adminApiRequest(`/chat/threads${q.trim()?`?q=${encodeURIComponent(q.trim())}`:""}`);return(payload?.items||[]).map(normalizeThread).filter(t=>t.messages.length>0);}
export async function getThread(id){const p=await adminApiRequest(`/chat/threads/${encodeURIComponent(id)}`);return p?.thread?normalizeThread(p.thread):null;}
export async function getChatStats(){const p=await adminApiRequest("/chat/stats");return p?.stats||{total:0,unreadThreads:0,totalUnread:0,resolved:0};}
export async function sendReply(threadId,text){const p=await adminApiRequest(`/chat/threads/${encodeURIComponent(threadId)}/messages`,{method:"POST",body:{text}});return p?.thread?normalizeThread(p.thread):null;}
export async function markRead(threadId){const p=await adminApiRequest(`/chat/threads/${encodeURIComponent(threadId)}/read`,{method:"POST"});return p?.thread?normalizeThread(p.thread):null;}
let socket=null;let listeners=new Set();
export function subscribeToThreads(callback){let active=true;let interval=window.setInterval(()=>{if(active)callback()},15000);getAdminAccessToken().then(token=>{if(!active||!window.io||!token)return;socket=window.io(import.meta.env.VITE_ADMIN_API_BASE_URL,{transports:["websocket","polling"],reconnection:true,auth:{accessToken:token}});socket.on("chat:message",()=>{if(active)callback()});});return()=>{active=false;window.clearInterval(interval);if(socket){socket.disconnect();socket=null}listeners.clear()};}
export async function subscribeToThread(threadId,callback){const token=await getAdminAccessToken();if(!window.io||!token)return()=>{};const s=window.io(import.meta.env.VITE_ADMIN_API_BASE_URL,{transports:["websocket","polling"],reconnection:true,auth:{accessToken:token}});s.on("connect",()=>s.emit("chat:join",{threadId}));s.on("chat:message",p=>{if(p.threadId===threadId)callback(p)});return()=>s.disconnect();}
