import { apiRequest, getStoredAccessToken } from "./api";
const GUEST_KEY = "rns_chat_guest_id_v1";
const CHAT_TOKEN_KEY = "rns_chat_guest_token_v1";
let socket = null;
let socketThreadId = null;
let socketListeners = new Set();
function makeId(prefix="m"){return `${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;}
export function getOrCreateGuestId(){ if(typeof window==="undefined") return "server"; try{let gid=localStorage.getItem(GUEST_KEY);if(!gid){gid=makeId("guest");localStorage.setItem(GUEST_KEY,gid)}return gid}catch{return "guest_temp"} }
function getChatToken(){return typeof window!=="undefined"?localStorage.getItem(CHAT_TOKEN_KEY)||"": "";}
function setChatToken(token){if(token&&typeof window!=="undefined")localStorage.setItem(CHAT_TOKEN_KEY,token)}
function headers(){const token=getChatToken();return token?{"x-chat-token":token}:{};}
function normalize(thread, fallback={}){return {id:thread.threadId||fallback.id,customerName:thread.customerName||fallback.name||"Guest",customerEmail:thread.customerEmail||fallback.email||"",messages:(thread.messages||[]).map(m=>({id:m._id||m.id||makeId(),from:m.from,text:m.text,ts:new Date(m.ts).getTime(),readByCustomer:m.readByCustomer===true,readByAdmin:m.readByAdmin===true})),updatedAt:thread.updatedAt?new Date(thread.updatedAt).getTime():Date.now(),status:thread.status||"open"};}
export async function getOrCreateThread(threadId, customerName, customerEmail){const authenticated=Boolean(getStoredAccessToken());const response=await apiRequest("/chat/threads",{method:"POST",body:{threadId,customerName,customerEmail},authRequired:authenticated,headers:authenticated?{}:headers()});if(response.chatToken)setChatToken(response.chatToken);return normalize(response.thread||{}, {id:threadId,name:customerName,email:customerEmail});}
export async function getThread(threadId){const response=await apiRequest(`/chat/threads/${encodeURIComponent(threadId)}`,{headers:headers(),authRequired:Boolean(getStoredAccessToken())});return normalize(response.thread||{},{id:threadId});}
export async function sendMessage(threadId,text){const response=await apiRequest(`/chat/threads/${encodeURIComponent(threadId)}/messages`,{method:"POST",body:{text},headers:headers(),authRequired:Boolean(getStoredAccessToken())});return normalize(response.thread||{},{id:threadId});}
export async function markRead(threadId){const response=await apiRequest(`/chat/threads/${encodeURIComponent(threadId)}/read`,{method:"POST",headers:headers(),authRequired:Boolean(getStoredAccessToken())});return normalize(response.thread||{},{id:threadId});}
function connectSocket(threadId,onUpdate){ if(!window.io)return null; if(socket&&socketThreadId===threadId){socketListeners.add(onUpdate);return ()=>socketListeners.delete(onUpdate);} if(socket){socket.disconnect();socket=null;} socketThreadId=threadId; const auth=getStoredAccessToken()?{accessToken:getStoredAccessToken()}:{chatToken:getChatToken()}; socket=window.io(import.meta.env.VITE_API_BASE_URL,{transports:["websocket","polling"],reconnection:true,reconnectionAttempts:Infinity,auth}); socket.on("connect",()=>socket.emit("chat:join",{threadId})); socket.on("chat:message",payload=>{if(payload.threadId!==threadId)return; for(const cb of socketListeners)cb(payload);}); socket.on("disconnect",()=>{}); socketListeners.add(onUpdate); return ()=>socketListeners.delete(onUpdate);}
export function subscribeToChatUpdates(threadId,onUpdate){let active=true;let unsubscribe=connectSocket(threadId,onUpdate);const refresh=async()=>{if(!active)return;try{onUpdate(await getThread(threadId))}catch{}};const interval=window.setInterval(refresh,15000);refresh();return()=>{active=false;window.clearInterval(interval);unsubscribe?.();if(socket&&socketListeners.size===0){socket.disconnect();socket=null;socketThreadId=null;}};}
